spring:
  application:
    name: main-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:8432/ewm-db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      defer-datasource-initialization: true
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  stats-server:
    name: stats-server

logging:
  level:
    "org.springframework.web": DEBUG
    "org.springframework.web.servlet": DEBUG
    "org.springframework.web.filter": DEBUG
    "ru.practicum": INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema.internal: DEBUG

server:
  port: 0