spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: ru.practicum.kafka.deserializer.UserActionDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        specific.avro.reader: true
      poll-timeout: 100ms

    producer:
      client-id: aggregator-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
      acks: all

app:
  kafka:
    topics:
      user-actions: "stats.user-actions.v1"
      events-similarity: "stats.events-similarity.v1"

logging:
  level:
    practicum.stats: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
